name: Computer Language Benchmark Game
author: Dan Mateas
description: Run Benchmarks - Python 3.9

services:
  gcb-clbg-python-3-9:
    image: gcb_clbg_python_3_9
    build:
      context: ./python
      dockerfile: Dockerfile-3-9

flow:
  - name: binary-trees
    container: gcb-clbg-python-3-9
    commands:
      - type: console
        shell: bash
        command: cd binary-trees/ && python3 binarytrees.py 21
  - name: fannkuch-redux
    container: gcb-clbg-python-3-9
    commands:
      - type: console
        shell: bash
        command: cd fannkuch-redux/ && python3 fannkuchredux.py 12
  - name: fasta
    container: gcb-clbg-python-3-9
    commands:
      - type: console
        shell: bash
        command: cd fasta/ && python3 fasta.py 25000000
