name: Computer Language Benchmark Game
author: Dan Mateas
description: Run Benchmarks - Mojo

services:
  gcb-clbg-python-mojo:
    image: gcb_clbg_python_mojo
    build:
      context: ./python
      dockerfile: Dockerfile-Mojo


flow:
  - name: binary-trees
    container: gcb-clbg-python-mojo
    commands:
      - type: console
        shell: sh
        command: cd binary-trees/ && mojo binarytrees.mojo
  - name: fannkuch-redux
    container: gcb-clbg-python-mojo
    commands:
      - type: console
        shell: sh
        command: cd fannkuch-redux/ && mojo fannkuchredux.mojo
  - name: fasta
    container: gcb-clbg-python-mojo
    commands:
      - type: console
        shell: sh
        command: cd fasta/ && mojo fasta.mojo